### ISSUE TITLE
Consider migration to OpenLayers 3?

### ISSUE THREAD

**Issue by sebasbaumh** [geosdi/GWT-OpenLayers#25]
As OpenLayers 3 has landed (it is now the main version on http://openlayers.org/), I would like to consider moving from OpenLayers 2 to 3.

OpenLayers 3 supports Canvas, WebGL and is ready for 3D (e.g. see http://gis.stackexchange.com/questions/62192/is-it-a-good-idea-to-migrate-to-openlayers-3-now).
I often read it is a rewrite of version 2, so the question comes up whether GWT-OpenLayers could transition to 3 or also needs a rewrite.
In case a rewrite is needed, the effort might not be worth to do it now - so what is your opinion on that?

Best regards,

Sebastian

**Comment by WTBenjamin** [comment]
Any update on moving from OpenLayers 2 to 3?

**Comment by glascaleia** [comment]
Hi All,
sorry fo delay. In geoSDI we are working on a lot of project and we have no
time to schedule at moment this upgrade.
In our projects we are using both OpenLayers 2 and Leaflet.
Regards Giuseppe

2015-11-26 12:13 GMT+01:00 WTBenjamin <notifications@github.com>:

> Any update on moving from OpenLayers 2 to 3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geosdi/GWT-OpenLayers/issues/25#issuecomment-159884950>
> .
>



-- 
Giuseppe La Scaleia
CNR - IMAA
geoSDI
Sviluppo Software

C.da S. Loja
85050  Tito Scalo - POTENZA (PZ)
Italia

phone:  +39 0971427305
fax:      +39 0971 427271
mob:    +39 3312174998
mail:     giuseppe.lascaleia@geosdi.org
skype:  glascaleia

web:     http://www.geosdi.org

**Comment by sebasbaumh** [comment]
@WTBenjamin : you might have a look on [TDesjardins](https://github.com/TDesjardins/GWT-OL3-Playground) library and [my fork](https://github.com/sebasbaumh/gwt-ol3), which adds some functionality to it.
You will have to adapt to the new class structure of OpenLayers 3 nevertheless as it is a thin wrapper around it.

**Comment by sebasbaumh** [comment]
I close this issue now as [gwt-ol3](https://github.com/TDesjardins/gwt-ol3) has become pretty mature since the creation of this issue and provides a good and very thin wrapper now for OpenLayers 3.
