### ISSUE TITLE
LineString class does not work

### ISSUE THREAD

**Issue by FredericKruger** [geosdi/GWT-OpenLayers#30]
Hello,

I seem to have a slight Problem with the LineString Class. Here is my code:

Point[] linePoints = {new Point(145, -40), new Point(147, 42)};
LineString l = new LineString(linePoints);

The Problem is with the second line. There the program stops, and nothing is displayed. I'm not able to find a solution to this problem. Could anyone help me with it ?

Thank you very much.
F. K.

**Comment by FredericKruger** [comment]
Hello again,

it seems like the Constructor does not want to work for me. Am I doing somthing wrong ?

Thank you for your help.
F.K.

**Comment by TDesjardins** [comment]
Hi Frederic,

I suppose that the custructor isn't the problem. I have successfully run some Unit tests which contain creating LineString-geometries. I have also integrate your code in the tests and it works fine. Can you provide more information about the problem, e.g stacktrace, browser, GWT version?

Regards

Tino

**Comment by FredericKruger** [comment]
Hi Tino,

thank you very much for your answer. I figured out the Problem: I needed to add the following line to the *.html file :<script src="project/js/gwt-openlayers/util.js"></script>
It was specified nowhere that I needed it though.
Thank you very much though :) I apreciate your help.

Regards
Frederic
