### ISSUE TITLE
getCentroid of Collection

### ISSUE THREAD

**Issue by vitalidze** [geosdi/GWT-OpenLayers#31]
According to [documentation of OpenLayers 2.13.1](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Geometry/Collection-js.html#OpenLayers.Geometry.Collection.getCentroid) there is an `getCentroid(boolean)` method in `Collection` geometry. Why java wrapper class don't implement it? I don't mind filing a pull request containing this change.

**Comment by glascaleia** [comment]
Added

**Comment by vitalidze** [comment]
Big thanks for such quick reply and action. I have two questions:

1) Why have you added big `Boolean` as the `getCentroid()` argument and not primitive one?

2) How to get latest version? Should I have a repository `OSS-Sonatype-Snapshots` in my `pom.xml`? I couldn't find 1.1-SNAPSHOT in maven central.

**Comment by glascaleia** [comment]
Hi,
for question 1 no particular reason.
Yes you must have this repository in your pom 
http://oss.sonatype.org/content/repositories/snapshots.
Regards Giuseppe

**Comment by vitalidze** [comment]
Thanks again. So do you mind changing it to primitive `boolean` because from my point of view it is more correct. Also from my understanding code of OpenLayers they expect argument to not be null (maybe I'm wrong). Last, I can't imagine a case when you should supply there a `null` `Boolean` value.

**Comment by glascaleia** [comment]
Yes , I looked  the openlayers code and I think you're right .
I do it ASAP.
Regards Giuseppe

**Comment by vitalidze** [comment]
Looks good, thanks!

**Comment by vitalidze** [comment]
What stops from releasing stable version 1.1?

**Comment by glascaleia** [comment]
Nothing,
we wait to add some example in the showcase and no time to do it.
I will planning this operation for the end of month
Regards Giuseppe

**Comment by vitalidze** [comment]
@glascaleia any chance to release the new version of gwt-openlayers?
