### ISSUE TITLE
Conflicting copyright statements in header.txt and licence.txt

### ISSUE THREAD

**Issue by tazle** [geosdi/GWT-OpenLayers#43]
Hi,

It seems that when the original licence.txt was added, @ecommandeur thought that the appropriate copyright holder for the project was "GWT OpenLayers Team". However, then @glascaleia later added the copyright headers to all files, the copyright was changed to "sourceforce".

Questions:
- Is sourceforge the SourceForge website?
- Was there an actual transfer of copyright from the authors to some corporate entity backing the SourceForce website?
- If not, could the original copyright statement perhaps be restored?

licence.txt:
```
Copyright 2010 GWT OpenLayers Team...
```

header.txt:
```
Copyright 2015 sourceforge....
```

**Comment by glascaleia** [comment]
Yes sorry
